"""create_cash_flow_table

Revision ID: 002_create_cash_flow
Revises: 4daa9fa7b13d
Create Date: 2025-11-21 07:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002_create_cash_flow'
down_revision: Union[str, None] = '4daa9fa7b13d'  # customer 테이블 마이그레이션 ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monthly_average', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monthly_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('data_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_record_id'], ['data_record.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_id'), 'cash_flow', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_item_name'), 'cash_flow', ['item_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_flow_item_name'), table_name='cash_flow')
    op.drop_index(op.f('ix_cash_flow_id'), table_name='cash_flow')
    op.drop_table('cash_flow')
    # ### end Alembic commands ###

